M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2025-11-06T08:32:30+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T08:32:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C8.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C15.000
%
G90
G05
T2
X34.55Y-93.75
X59.5Y-93.75
T3
X24.5Y-95.95
X69.6Y-95.95
T4
X83.35Y-93.5
X126.75Y-94.0
T5
X150.75Y-90.0
X181.0Y-90.0
T1
G00X103.5Y-99.0
M15
G01X113.5Y-99.0
M16
G05
M30
